language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.3
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository

install:
    - yes | $ANDROID_HOME/tools/bin/sdkmanager "tools"
    - yes | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools"

licenses:
    - 'android-sdk-license-.+'

script: ./gradlew build || (cat /home/travis/build/apiote/Bimba/app/build/reports/lint-results.html; false)
