language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.3
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platform-tools"

script: ./gradlew build || (cat /home/travis/build/apiote/Bimba/app/build/reports/lint-results.html; false)
